baseurl = "https://nicolaiarocci.com/"
title = "Nicola Iarocci"
copyright = "All rights reserved"
theme = "casper"
languagecode = "en-US"
paginate = 5
pluralizelisttitles = false
PygmentsCodeFences = true

[[menu.main]]
name = "Blog"
url = "/"
weight = 11

[[menu.main]]
name = "About"
url = "/about"
weight = 10

[[menu.main]]
name = "Open Source"
url = "/opensource"
weight = 9


[[menu.main]]
name = "Speaking"
url = "/talks"
weight = 8

[[menu.main]]
name = "Reading"
url = "/books-i-have-read"
weight = 7


[[menu.main]]
name = "MongoDB"
url = "/il-piccolo-libro-di-mongodb-edizione-italiana"
weight = 6

[[menu.main]]
pre = "<h3>Subscribe</h3>"
name = "New posts via mail"
url = "http://eepurl.com/b-_Pzz"
weight = -200

[[menu.main]]
name = "RSS feed"
url = "https://nicolaiarocci.com/index.xml"
weight = -210

[[menu.main]]
pre = "<h3>Follow me</h3>"
name = "Twitter"
url = "https://twitter.com/nicolaiarocci"
weight = -300

[[menu.main]]
name = "Github"
url = "https://github.com/nicolaiarocci"
weight = -310

[[menu.main]]
name = "Stack Overflow"
url = "https://stackoverflow.com/users/323269/nicola-iarocci?tab=profile"
weight = -320

[[menu.main]]
name = "Speaker Deck"
url = "http://speakerdeck.com/u/nicola"
weight = -330

[[menu.main]]
name = "LinkedIn"
url = "http://www.linkedin.com/in/nicolaiarocci"
weight = -340

[params]
author = "Nicola Iarocci"
authorlocation = "Ravenna, Italy"
authorwebsite = "https://nicolaiarocci.com"
description = "Software Craftsman"
metadescription = "This is the personal website of Nicola Iarocci, Software Craftsman."
bio = "Software Craftsman"
#cover = "images/hacking.jpg"
logo = "images/avatar.png"
customCSS = ["css/custom.css"]
shareenabled = false

#githubName = "nicolaiarocci"
#twitterName = "nicolaiarocci"
#linkedinName = "nicolaiarocci"

googleAnalyticsUserID = "UA-19006041-1"
hideHUGOSupport = true

[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
